### ISSUE TITLE
Pins for RS485?

### ISSUE THREAD

**Issue by Plawasan** [makstech/esphome-es32a08-expansion-board-example#2]
Hi, thanks for the yaml, I was able to get everything work as expected with the only exception of uart pins for RS485/modbus... any idea what those are?

Thanks!

**Comment by Plawasan** [comment]
Some progress... I've emailed eletechsup, they shared the following with me:

https://485io.com/eletechsup/ES32A08-ES33B08-1.rar

as part of that there's the following RS485 vscode example:

```
#define ECHO_TEST_TXD   1
#define ECHO_TEST_RXD   3

// RTS for RS485 Half-Duplex Mode manages DE/~RE
#define ECHO_TEST_RTS   22

// CTS is not used in RS485 Half-Duplex Mode
#define ECHO_TEST_CTS   (UART_PIN_NO_CHANGE)

#define BUF_SIZE        (127)
#define BAUD_RATE       115200

// Read packet timeout
#define PACKET_READ_TICS        (100 / portTICK_PERIOD_MS)
#define ECHO_TASK_STACK_SIZE    (2048)
#define ECHO_TASK_PRIO          (10)
#define ECHO_UART_PORT          (CONFIG_ECHO_UART_PORT_NUM)

// Timeout threshold for UART = number of symbols (~10 tics) with unchanged state on receive pin
#define ECHO_READ_TOUT          (3) // 3.5T * 8 = 28 ticks, TOUT=3 -> ~24..33 ticks

```

I've tried to replicate that in ESPHome:

relevant bits:

```
logger:
  baud_rate: 0

uart:
  id: mod_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200

modbus:
  id: modbus1
  uart_id: mod_bus

modbus_controller:
  - id: ext_relay_board
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10 

switch:
  - platform: output
    id: master_irrigation_valve_switch
    output: ext_relay_2
    name: "${esp_name} Master Irrigation Valve Switch"
    internal: True

output:
  - platform: modbus_controller
    id: ext_relay_2
    modbus_controller_id: ext_relay_board
    address: 1
    register_type: coil
```

but I'm not seeing any traffic on the bus (the relay board has a LED indicator that flashes when it receives data). I have tested the same exact external relay board with a different ESP32 and a separate TTL to RS485 interface and all worked OK.

I've also noticed this on the device page at https://devices.esphome.io/devices/ES32A08

known limitations
**RS485 is not enabled** but would work using GPIO1 -> TXD and GPIO3 -> RXD

So..any idea how to get it to work before I go and solder a twisted pair directly to some unused pins on the ESP32 and use an external TTL to RS485 adapter?

**Comment by makstech** [comment]
I tried the onboard RS485 myself and ended up wasting a lot of time on it. It seems very likely there’s a hardware bug that makes the onboard RS485 unusable. Here’s how I came to that conclusion in an official ESPHome Discord: https://discord.com/channels/429907082951524364/1367919664864301197/1367919667963887676

To get RS485 working, I soldered an external RS485 module to the pins for the onboard buttons, and now it works perfectly. I used a MAX485 module, which uses 3 pins:
```yaml
uart:
  tx_pin: GPIO19
  rx_pin: GPIO23
  baud_rate: 9600

modbus:
  flow_control_pin: GPIO21
```
You can also use simpler 2-pin modules with this setup.

![Image](https://github.com/user-attachments/assets/2dab4954-c6f7-4042-85c6-44581d8396b0)

**Comment by Plawasan** [comment]
Thanks, I've arrived at pretty much the same conclusion - I can actually communicate with the relay board but I never get any response from it, i.e. TX works but RX does not (at least in my amateur view).

I was thinking of soldering the external module to the pins of the ESP but using the keys is a neater idea..

I'll send the link to the discord to the manufacturer, I was communicating with them via Whatsapp but I have little hope that will actually solve anything..

**Comment by Zenosfr** [comment]
Hello,

My 2 cents on this, i do think there is no hardware issue but USB MUST BE DISCONNECTED of the ESP32 module and the logger disabled for it to work as the UART pin are shared between the 485 transciever and the USB chip.

This is my working configuration with Esphome 2025.10.3 and esp-idf-v5.4.2 (also tested successfully with esp-idf-v5.4.1)


```
esphome:
  name: myhardname
  friendly_name: mygentlename

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Disable logging
logger:
  baud_rate: 0


uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  stop_bits: 1

modbus:
  id: modbus1
  flow_control_pin: GPIO22
```


For testing and debugging i did configure the 3 gpio (1 3 and 22) as switch to be able to toggle them manually and measure the response of the 485 driver to the different state.
